### ISSUE TITLE
精度对齐

### ISSUE THREAD

**Issue by lovejing0306** [LongxingTan/Yolov5#3]
## ❔Question

你好，请问您开源的模型有和原始作者的开源模型做精度对齐了码？

**Comment by LongxingTan** [comment]
没有，我自己只在[yymnist](https://github.com/YunYang1994/yymnist)上尝试了一下。效果超过yolov3，其他都还没时间实验，只能做个简单参考

**Comment by lovejing0306** [comment]
> 没有，我自己只在[yymnist](https://github.com/YunYang1994/yymnist)上尝试了一下。效果超过yolov3，其他都还没时间实验，只能做个简单参考

感谢回复，我稍后做个验证
